# Generated by Django 6.0.3 on 2026-03-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfApp', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductUpdate',
        ),
    ]
