# Generated by Django 6.0.3 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfApp', '0003_rename_product_productupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
